name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run script
        id: script
        run: bash gradlew

      - name: Setup Android SDK
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        uses: android-actions/setup-android@v2 

      - uses: actions/setup-java@v3
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: clone, build mindustry
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        run: |
          mkdir .tmp
          mkdir .output
          cd .tmp
          git clone --depth 1 --branch erekir https://github.com/anuken/mindustry/
          cd mindustry
          bash gradlew tools::pack desktop::dist server::dist android::assembleDebug

          mv desktop/build/libs/*.jar ../../.output/Mindustry-desktop.jar
          mv server/build/libs/*.jar ../../.output/Mindustry-server.jar
          mv `find -wholename ./android/build/outputs/apk/*.apk` ../../.output/Mindustry-android-unsigned.apk

          cd ../..
          rm -rf .tmp

      - name: Generate a key and sign the android build
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        run: |
          cd .output

          password="DEBUG_PASSWORD"
          alias="DEBUG_ALIAS"

          echo -e "$password\n$password\n\n\n\n\n\n\nyes" | keytool -genkey -v -keystore debug.keystore -alias $alias -keyalg RSA -keysize 2048 -validity 10000
          echo $password | jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore -keypass $password Mindustry-android-unsigned.apk $alias
          mv Mindustry-android-unsigned.apk Mindustry-android.apk

      - name: Upload desktop build
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .output/Mindustry-desktop.jar
          tag: ${{ github.ref }}
        
      - name: Upload server build
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .output/Mindustry-server.jar
          tag: ${{ github.ref }}
        
      - name: Upload android build
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .output/Mindustry-android.apk
          tag: ${{ github.ref }}
        
      - name: Cleanup
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        run: |
          rm -rf .output
          rm -f app/RESULT

      - name: Upload last state
        if: ${{ steps.script.outputs.SUCCESS }} == "true"
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add app/LAST_UPDATE
          git commit -am "Auto-update"
          git push
