name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine version number
        env:
          runNumber: ${{ github.run_number }}
        run: |
          echo "version=$(( $runNumber + 30000 ))" >> $GITHUB_ENV
          echo "Version $version"

      - name: Run script
        id: script
        run: |
          bash gradlew run

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2 

      - name: Setup JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      
      - name: Setup apksigner
        run: sudo apt install apksigner -y

      - name: Clone, build mindustry
        run: |
          mkdir .tmp
          mkdir .output
          cd .tmp
          git clone --depth 1 --branch erekir https://github.com/anuken/mindustry/
          cd mindustry
          bash gradlew desktop::dist -Pbuildversion=${version} -PversionType=bleeding-edge --stacktrace
          bash gradlew server::dist -Pbuildversion=${version} -PversionType=bleeding-edge --stacktrace
          bash gradlew android::assembleDebug -Pbuildversion=${version} -PversionType=bleeding-edge --stacktrace

          mv desktop/build/libs/*.jar ../../.output/Mindustry-desktop.jar
          mv server/build/libs/*.jar ../../.output/Mindustry-server.jar
          mv `find -wholename ./android/build/outputs/apk/*.apk` ../../.output/Mindustry-android-unsigned.apk

          cd ../..
          rm -rf .tmp

      - name: Sign the android build
        env:
          keyBase64: ${{ secrets.BASE64_KEY }}
          alias: mindbe
          password: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd .output

          echo $keyBase64 > berelease.keystore.base64
          base64 --decode berelease.keystore.base64 > berelease.keystore

          echo $password | apksigner sign --ks-key-alias $alias --ks berelease.keystore Mindustry-android-unsigned.apk
          mv Mindustry-android-unsigned.apk Mindustry-android.apk

      - name: Upload desktop build
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .output/Mindustry-desktop.jar
          tag: ${{ env.version }}
          body: ${{ steps.script.outputs.MESSAGE }}
        
      - name: Upload server build
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .output/Mindustry-server.jar
          tag: ${{ env.version }}
          body: ${{ steps.script.outputs.MESSAGE }}
        
      - name: Upload android build
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .output/Mindustry-android.apk
          tag: ${{ env.version }}
          body: ${{ steps.script.outputs.MESSAGE }}
        
      - name: Cleanup
        run: |
          rm -rf .output
          rm -f app/RESULT

      - name: Upload last state
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add app/LAST_UPDATE
          git commit -am "Auto-update"
          git push
